clasificacion = 
  {
    filters: {},
    competition: {
      id: 2014,
      area: {
        id: 2224,
        name: "Spain",
      },
      name: "Primera Division",
      code: "PD",
      plan: "TIER_ONE",
      lastUpdated: "2021-04-17T00:00:28Z",
    },
    season: {
      id: 380,
      startDate: "2021-08-13",
      endDate: "2022-05-22",
      currentMatchday: 9,
      winner: null,
    },
    standings: [
      {
        stage: "REGULAR_SEASON",
        type: "TOTAL",
        group: null,
        table: [
          {
            position: 1,
            team: {
              id: 86,
              name: "Real Madrid CF",
              crestUrl: "https://crests.football-data.org/86.svg",
            },
            playedGames: 8,
            form: null,
            won: 5,
            draw: 2,
            lost: 1,
            points: 17,
            goalsFor: 22,
            goalsAgainst: 10,
            goalDifference: 12,
          },
          {
            position: 2,
            team: {
              id: 78,
              name: "Club Atlético de Madrid",
              crestUrl: "https://crests.football-data.org/78.svg",
            },
            playedGames: 8,
            form: null,
            won: 5,
            draw: 2,
            lost: 1,
            points: 17,
            goalsFor: 11,
            goalsAgainst: 6,
            goalDifference: 5,
          },
          {
            position: 3,
            team: {
              id: 92,
              name: "Real Sociedad de Fútbol",
              crestUrl: "https://crests.football-data.org/92.svg",
            },
            playedGames: 8,
            form: null,
            won: 5,
            draw: 2,
            lost: 1,
            points: 17,
            goalsFor: 11,
            goalsAgainst: 7,
            goalDifference: 4,
          },
          {
            position: 4,
            team: {
              id: 559,
              name: "Sevilla FC",
              crestUrl: "https://crests.football-data.org/559.svg",
            },
            playedGames: 7,
            form: null,
            won: 4,
            draw: 2,
            lost: 1,
            points: 14,
            goalsFor: 10,
            goalsAgainst: 3,
            goalDifference: 7,
          },
          {
            position: 5,
            team: {
              id: 79,
              name: "CA Osasuna",
              crestUrl: "https://crests.football-data.org/79.svg",
            },
            playedGames: 8,
            form: null,
            won: 4,
            draw: 2,
            lost: 2,
            points: 14,
            goalsFor: 11,
            goalsAgainst: 11,
            goalDifference: 0,
          },
          {
            position: 6,
            team: {
              id: 87,
              name: "Rayo Vallecano de Madrid",
              crestUrl: "https://crests.football-data.org/87.svg",
            },
            playedGames: 8,
            form: null,
            won: 4,
            draw: 1,
            lost: 3,
            points: 13,
            goalsFor: 13,
            goalsAgainst: 8,
            goalDifference: 5,
          },
          {
            position: 7,
            team: {
              id: 77,
              name: "Athletic Club",
              crestUrl: "https://crests.football-data.org/77.svg",
            },
            playedGames: 8,
            form: null,
            won: 3,
            draw: 4,
            lost: 1,
            points: 13,
            goalsFor: 7,
            goalsAgainst: 4,
            goalDifference: 3,
          },
          {
            position: 8,
            team: {
              id: 95,
              name: "Valencia CF",
              crestUrl: "https://crests.football-data.org/95.svg",
            },
            playedGames: 8,
            form: null,
            won: 3,
            draw: 3,
            lost: 2,
            points: 12,
            goalsFor: 12,
            goalsAgainst: 8,
            goalDifference: 4,
          },
          {
            position: 9,
            team: {
              id: 81,
              name: "FC Barcelona",
              crestUrl: "https://crests.football-data.org/81.svg",
            },
            playedGames: 7,
            form: null,
            won: 3,
            draw: 3,
            lost: 1,
            points: 12,
            goalsFor: 11,
            goalsAgainst: 7,
            goalDifference: 4,
          },
          {
            position: 10,
            team: {
              id: 90,
              name: "Real Betis Balompié",
              crestUrl: "https://crests.football-data.org/90.svg",
            },
            playedGames: 8,
            form: null,
            won: 3,
            draw: 3,
            lost: 2,
            points: 12,
            goalsFor: 11,
            goalsAgainst: 9,
            goalDifference: 2,
          },
          {
            position: 11,
            team: {
              id: 94,
              name: "Villarreal CF",
              crestUrl: "https://crests.football-data.org/94.svg",
            },
            playedGames: 7,
            form: null,
            won: 2,
            draw: 5,
            lost: 0,
            points: 11,
            goalsFor: 8,
            goalsAgainst: 3,
            goalDifference: 5,
          },
          {
            position: 12,
            team: {
              id: 89,
              name: "RCD Mallorca",
              crestUrl: "https://crests.football-data.org/89.svg",
            },
            playedGames: 8,
            form: null,
            won: 3,
            draw: 2,
            lost: 3,
            points: 11,
            goalsFor: 7,
            goalsAgainst: 12,
            goalDifference: -5,
          },
          {
            position: 13,
            team: {
              id: 80,
              name: "RCD Espanyol de Barcelona",
              crestUrl: "https://crests.football-data.org/80.svg",
            },
            playedGames: 8,
            form: null,
            won: 2,
            draw: 3,
            lost: 3,
            points: 9,
            goalsFor: 6,
            goalsAgainst: 8,
            goalDifference: -2,
          },
          {
            position: 14,
            team: {
              id: 285,
              name: "Elche CF",
              crestUrl: "https://crests.football-data.org/285.svg",
            },
            playedGames: 8,
            form: null,
            won: 2,
            draw: 3,
            lost: 3,
            points: 9,
            goalsFor: 5,
            goalsAgainst: 8,
            goalDifference: -3,
          },
          {
            position: 15,
            team: {
              id: 264,
              name: "Cádiz CF",
              crestUrl: "https://crests.football-data.org/264.svg",
            },
            playedGames: 8,
            form: null,
            won: 1,
            draw: 4,
            lost: 3,
            points: 7,
            goalsFor: 7,
            goalsAgainst: 11,
            goalDifference: -4,
          },
          {
            position: 16,
            team: {
              id: 558,
              name: "RC Celta de Vigo",
              crestUrl: "https://crests.football-data.org/558.svg",
            },
            playedGames: 8,
            form: null,
            won: 2,
            draw: 1,
            lost: 5,
            points: 7,
            goalsFor: 7,
            goalsAgainst: 11,
            goalDifference: -4,
          },
          {
            position: 17,
            team: {
              id: 83,
              name: "Granada CF",
              crestUrl: "https://crests.football-data.org/83.svg",
            },
            playedGames: 8,
            form: null,
            won: 1,
            draw: 3,
            lost: 4,
            points: 6,
            goalsFor: 6,
            goalsAgainst: 12,
            goalDifference: -6,
          },
          {
            position: 18,
            team: {
              id: 88,
              name: "Levante UD",
              crestUrl: "https://crests.football-data.org/88.svg",
            },
            playedGames: 8,
            form: null,
            won: 0,
            draw: 4,
            lost: 4,
            points: 4,
            goalsFor: 6,
            goalsAgainst: 13,
            goalDifference: -7,
          },
          {
            position: 19,
            team: {
              id: 263,
              name: "Deportivo Alavés",
              crestUrl: "https://crests.football-data.org/263.svg",
            },
            playedGames: 7,
            form: null,
            won: 1,
            draw: 0,
            lost: 6,
            points: 3,
            goalsFor: 2,
            goalsAgainst: 12,
            goalDifference: -10,
          },
          {
            position: 20,
            team: {
              id: 82,
              name: "Getafe CF",
              crestUrl: "https://crests.football-data.org/82.svg",
            },
            playedGames: 8,
            form: null,
            won: 0,
            draw: 1,
            lost: 7,
            points: 1,
            goalsFor: 3,
            goalsAgainst: 13,
            goalDifference: -10,
          },
        ],
      },
    ],
  };

